"""Modificações no table usuarios.

Revision ID: affe86b532c0
Revises: 6324b4bc63d2
Create Date: 2026-02-23 09:52:14.540877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'affe86b532c0'
down_revision = '6324b4bc63d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('tipo', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('tipo')
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###
