"""feat: Modificação do model paciente.

Revision ID: bc6b631a8197
Revises: fcd7dd520b83
Create Date: 2026-02-26 17:23:33.035189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc6b631a8197'
down_revision = 'fcd7dd520b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('idade_unidade', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('setor', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('leito', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('peso_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('altura_cm', sa.Float(), nullable=True))
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=14),
               nullable=True)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('sexo',
               existing_type=mysql.ENUM('MASCULINO', 'FEMININO'),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_pacientes_external_id'), ['external_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_external_id'))
        batch_op.alter_column('sexo',
               existing_type=mysql.ENUM('MASCULINO', 'FEMININO'),
               nullable=False)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=14),
               nullable=False)
        batch_op.drop_column('altura_cm')
        batch_op.drop_column('peso_kg')
        batch_op.drop_column('leito')
        batch_op.drop_column('setor')
        batch_op.drop_column('idade_unidade')
        batch_op.drop_column('idade')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
