"""corrigindo foreign key usuario

Revision ID: fcd7dd520b83
Revises: d35eabe948a6
Create Date: 2026-02-23 14:33:23.764299
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd7dd520b83'
down_revision = 'd35eabe948a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pacientes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=255), nullable=False),
        sa.Column('cpf', sa.String(length=14), nullable=False),
        sa.Column('data_nascimento', sa.Date(), nullable=False),
        sa.Column(
            'sexo',
            sa.Enum('MASCULINO', 'FEMININO', name='sexoenum'),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cpf'),
    )
    op.create_table(
        'ecg_exams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('paciente_id', sa.Integer(), nullable=False),
        sa.Column('data_exame', sa.DateTime(), nullable=True),
        sa.Column('frequencia_media', sa.Integer(), nullable=False),
        sa.Column('arquivo', sa.String(length=255), nullable=False),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['usuarios.id'],
        ),
        sa.ForeignKeyConstraint(
            ['paciente_id'],
            ['pacientes.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecg_exams')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
